general:

steps:
  mtaBuild:
    buildTarget: "CF"
  cloudFoundryDeploy:
    deployTool: "mtaDeployPlugin"
    deployType: "standard"
    cloudFoundry:
      org: "25f182abtrial"
      space: "piper-test"
      credentialsId: "CF_CREDENTIALSID"
